spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.OracleDriver
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:latest

embabel:
  models:
    defaultLlm: llama3.2:latest
  rag:
    oracle:
      name: oracle-store
      schemaName: scott
      contentElementTable: CONTENT_ELEMENTS
      embeddingDimension: 3
      similarityThresholdCeiling: 0.5
